### GET
GET http://localhost:5008/

### GET steden
GET http://localhost:5008/steden

//TODO api tests aanvullen

### GET weerstations:
GET http://localhost:5008/weerstations

### POST DoeMeting
POST http://localhost:5008/commands/meting-command

### GET metingen
GET http://localhost:5008/metingen

### GET weerbericht
GET http://localhost:5008/weerbericht

